### ISSUE TITLE
Pressing "Remove Watch" on the Watches screen with no row selected raises AttributeError

### ISSUE THREAD

**Issue by BenBradnick** [Observatory-Sciences/dls-pmac-control#1]
Steps to reproduce:

1. Open "Watches"
2. Press "Remove Watch"
3. Application crashes with uncaught Exception

```
Traceback (most recent call last):
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls_pmaccontrol/3.0.0b1/prefix/lib/python3.7/site-packages/dls_pmaccontrol/watches.py", line 73, in removeWatch
    varName = self.table.item(row, 0).text()
AttributeError: 'NoneType' object has no attribute 'text'
Aborted

```

This happens even when you have added a watch, because a row isn't selected by default.

**Comment by rjwills28** [comment]
Thanks for reporting this. We have now fixed this issue by ensuring that a row has been selected before trying to delete it.

For more details see commit: https://github.com/Observatory-Sciences/dls-pmac-control/commit/ae5bb96c680e2c988ab4aaac4360da69445f99d8

This fix has been included in the DLS 3.0.0b2 version.
