### ISSUE TITLE
ssh command line option

### ISSUE THREAD

**Issue by UrszulaNeuman** [Observatory-Sciences/dls-pmac-control#3]
dls-pmac-control.py doesn't seem to have the option to set the ssh protocol from command line. 
For tcpip we have dls-pmac-control.py -o tcpip. For ssh I would expect dls-pmac-control.py -o ssh. I tried but it comes back with tcpip selected instead of ssh.

**Comment by rjwills28** [comment]
Thanks for reporting this. We have now fixed this issue to ensure that `-o ssh` loads the GUI with the ssh option selected.

For more details see commit: https://github.com/Observatory-Sciences/dls-pmac-control/commit/047a79eda76c6d1930a2703b5c6f4c1aafa1f3ad

This fix has been included in the DLS 3.0.0b2 version.
