### ISSUE TITLE
Feature Request: Show the 7 segment display status for turbo pmacs

### ISSUE THREAD

**Issue by gilesknap** [Observatory-Sciences/dls-pmac-control#7]
Amp Status bits (7 Segment Display Status):

Mx90 – Amp Status word

Mx90 & 448 – Amp Status bits (but this isn't a valid on-line command so you need to use the Watch Window or PLC code below or do it manually with bitwise AND in the Windows calculator in programmer mode)

![image](https://user-images.githubusercontent.com/964827/154305000-a82795db-0719-4674-b523-9d00ffc23448.png)

**Comment by rjwills28** [comment]
This feature has been added to the released v3.0.0.
